from pyspark import SparkContext
from pyspark.sql import SQLContext

sc = SparkContext()
sqlContext = SQLContext(sc)

airportsData = sqlContext.read.format("com.databricks.spark.csv").\
    options(header="true",inferschema="true").\
    load("hdfs://localhost:9000/airports/airports-csv.csv")
# airportsData.show()
airportsData.registerTempTable("airports")

flightData = sqlContext.read.format("com.databricks.spark.csv").\
    options(header="true",inferschema="true").\
    load("hdfs://localhost:9000/air1998/1998.csv")
# flightData.show()
flightData.registerTempTable("flights")

# 离港时间在不同时间段的航班总数
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE DepTime BETWEEN 1901 AND 2359").show()
# 离港时间在不同时间段的航班总数
#
# 每天不同时间段的平均离港航班数量,按月统计
# print("month1")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 1 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 1 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 1 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 1 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 1 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month2")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 2 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 2 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 2 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 2 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 2 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month3")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 3 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 3 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 3 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 3 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 3 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month4")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 4 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 4 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 4 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 4 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 4 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month5")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 5 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 5 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 5 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 5 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 5 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month6")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 6 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 6 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 6 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 6 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 6 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month7")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 7 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 7 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 7 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 7 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 7 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month8")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 8 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 8 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 8 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 8 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 8 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month9")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 9 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 9 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 9 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 9 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 9 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month10")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 10 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 10 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 10 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 10 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 10 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month11")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 11 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 11 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 11 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 11 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 11 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")
# print("month12")
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 12 AND DepTime BETWEEN 0 AND 600").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 12 AND DepTime BETWEEN 601 AND 1000").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 12 AND DepTime BETWEEN 1001 AND 1400").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 12 AND DepTime BETWEEN 1401 AND 1900").show()
# sqlContext.sql("SELECT COUNT(FlightNum)/COUNT(DISTINCT DayofMonth) FROM flights WHERE Month = 12 AND DepTime BETWEEN 1901 AND 2359").show()
# print("---------------------------------------------")


# #到港航班延误时间为 0 的次数
# sqlContext.sql("SELECT DISTINCT Dest, COUNT(ArrDelay) AS delayTimes FROM flights where ArrDelay = 0 GROUP BY Dest ORDER BY delayTimes DESC").show()
# #到港航班延误时间为 0 的次数

#某飞机场总的到港次数
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE Dest = 'PHX'").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE Dest = 'ORD'").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE Dest = 'ATL'").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE Dest = 'LAS'").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE Dest = 'LAX'").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE Dest = 'DFW'").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE Dest = 'STL'").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE Dest = 'DAL'").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE Dest = 'HOU'").show()
# sqlContext.sql("SELECT COUNT(FlightNum) FROM flights WHERE Dest = 'OAK'").show()
#某飞机场总的到港次数

# # 1998年准点的到港航班的个数排名
# sqlContext.sql("SELECT DISTINCT state, SUM(delayTimes) AS s FROM (SELECT DISTINCT Dest, COUNT(ArrDelay) AS delayTimes FROM flights WHERE ArrDelay = 0 GROUP BY Dest ) a JOIN airports b ON a.Dest = b.iata GROUP BY state ORDER BY s DESC").show()
# # 1998年准点的到港航班的个数排名

# #1998 年内，延误最严重的十次航班及所在的离港机场(离港延误时间大于 60 分钟)
# sqlContext.sql("SELECT DISTINCT Origin, DepDelay FROM flights where DepDelay > 60 ORDER BY DepDelay DESC").show(10)
# #1998 年内，延误最严重的十次航班及所在的离港机场(离港延误时间大于 60 分钟)
